name: ruby gem
on: [push]

permissions:
  actions: write
  contents: read

jobs:
  test:
    permissions:
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - gemfiles/Gemfile-rails-7-1
          - gemfiles/Gemfile-rails-7-2
          - gemfiles/Gemfile-rails-8-0
          - gemfiles/Gemfile-rails-8-1
        ruby:
          - 3.4
    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      COVERAGE: true
    steps:
      - uses: actions/checkout@v5

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs bundle install and caches installed gems automatically
          bundler: ${{ env.BUNDLER_VERSION || 'latest' }}

      - name: Run rubocop
        run: bundle exec rubocop

      - name: Run tests
        run: bundle exec rspec

      - name: Publish code coverage
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: coverage/coverage.json
